//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIA_FlightBookingWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketChangesLog
    {
        public int logID { get; set; }
        public string ticID { get; set; }
        public string passport { get; set; }
        public string passengerName { get; set; }
        public string status { get; set; }
        public string resID { get; set; }
        public Nullable<decimal> charge { get; set; }
        public Nullable<System.DateTime> dateTimes { get; set; }
        public string operation { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
